apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sz4hkrlhg-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/sz4hkrlhg-dotnet-basic-gitops